apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-cdc
  template:
    metadata:
      labels:
        app: mongo-cdc
    spec:
      nodeSelector:
        node-pool-group: subscribers
      containers:
        - name: mongo-cdc
          image: asia-south1-docker.pkg.dev/blitzscale-dev-project/blitzscale-dev/mongo-cdc:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
      terminationGracePeriodSeconds: 5
